version: "3.6"

services:
  web:
    build: .
    stdin_open: false
    ports:
      - 8081:8081
    env_file: ./env/production.docker.env
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6.2.6
    volumes:
      - ./redis_data:/data
    restart: always